import type { BukuWajibItem, HeroContent, LandingStatItem } from '~/types/landing.types'

export const LANDING_HERO: HeroContent = {
  badgeText: 'Sistem Koperasi Terintegrasi #1',
  titleLine1: 'Transformasi Digital',
  titleHighlight: 'Koperasi Indonesia',
  description:
    'Kelola simpan pinjam, anggota, dan laporan 16 buku wajib dalam satu platform. Transparan, aman, dan disetujui standar nasional.',
  searchPlaceholder: 'Cari koperasi terdaftar...',
  searchButtonText: 'Cari',
  image: {
    src: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=2015&auto=format&fit=crop',
    alt: 'Dashboard Koperasi',
  },
  systemStatus: { label: 'Status Sistem', value: '100% Aman' },
}

export const LANDING_STATS: LandingStatItem[] = [
  { value: '100+', label: 'Koperasi Bergabung' },
  { value: '16', label: 'Modul Buku Wajib' },
  { value: 'Rp 50M+', label: 'Aset Dikelola' },
  { value: '100%', label: 'Keamanan Data' },
]

export const BUKU_WAJIB_LIST: BukuWajibItem[] = [
  {
    id: '01',
    title: 'Daftar Anggota',
    icon: 'i-lucide-users',
    desc: 'Pencatatan data lengkap anggota.',
    pengurus: 'Full Akses',
    anggota: 'Read-only',
    tamu: 'Terkunci',
  },
  {
    id: '02',
    title: 'Daftar Pengurus',
    icon: 'i-lucide-user-cog',
    desc: 'Susunan kepengurusan aktif.',
    pengurus: 'Full Akses',
    anggota: 'Read-only',
    tamu: 'Terkunci',
  },
  {
    id: '03',
    title: 'Daftar Pengawas',
    icon: 'i-lucide-shield-check',
    desc: 'Data pengawas koperasi.',
    pengurus: 'Full Akses',
    anggota: 'Read-only',
    tamu: 'Terkunci',
  },
  {
    id: '04',
    title: 'Simpanan Anggota',
    icon: 'i-lucide-piggy-bank',
    desc: 'Rekap pokok, wajib, sukarela.',
    pengurus: 'Bendahara',
    anggota: 'Pribadi',
    tamu: 'Terkunci',
  },
  {
    id: '05',
    title: 'Pinjaman Anggota',
    icon: 'i-lucide-hand-coins',
    desc: 'Riwayat pinjaman & angsuran.',
    pengurus: 'Bendahara',
    anggota: 'Pribadi',
    tamu: 'Terkunci',
  },
  {
    id: '06',
    title: 'Daftar Inventaris',
    icon: 'i-lucide-box',
    desc: 'Aset barang fisik koperasi.',
    pengurus: 'Sekretaris',
    anggota: 'Read-only',
    tamu: 'Read-only',
  },
  {
    id: '07',
    title: 'Notulen Rapat Anggota',
    icon: 'i-lucide-users-round',
    desc: 'Catatan hasil RAT tahunan.',
    pengurus: 'Sekretaris',
    anggota: 'Read-only',
    tamu: 'Read-only',
  },
  {
    id: '08',
    title: 'Notulen Rapat Pengurus',
    icon: 'i-lucide-briefcase',
    desc: 'Rapat internal pengurus.',
    pengurus: 'Ketua/Sek',
    anggota: 'Terkunci',
    tamu: 'Terkunci',
  },
  {
    id: '09',
    title: 'Notulen Rapat Pengawas',
    icon: 'i-lucide-gavel',
    desc: 'Catatan evaluasi pengawas.',
    pengurus: 'Ketua/Sek',
    anggota: 'Terkunci',
    tamu: 'Terkunci',
  },
  {
    id: '10',
    title: 'Daftar Karyawan',
    icon: 'i-lucide-contact',
    desc: 'Data staff operasional.',
    pengurus: 'Full Akses',
    anggota: 'Read-only',
    tamu: 'Read-only',
  },
  {
    id: '11',
    title: 'Buku Tamu',
    icon: 'i-lucide-book-open-check',
    desc: 'Kunjungan fisik & website.',
    pengurus: 'Full Akses',
    anggota: 'Tulis/Baca',
    tamu: 'Menulis',
  },
  {
    id: '12',
    title: 'Saran Anggota',
    icon: 'i-lucide-message-square',
    desc: 'Aspirasi dari anggota.',
    pengurus: 'Full Akses',
    anggota: 'Tulis/Baca',
    tamu: 'Menulis',
  },
  {
    id: '13',
    title: 'Saran Pengawas',
    icon: 'i-lucide-message-circle-warning',
    desc: 'Teguran dari pengawas.',
    pengurus: 'Full Akses',
    anggota: 'Terkunci',
    tamu: 'Terkunci',
  },
  {
    id: '14',
    title: 'Anjuran Pejabat',
    icon: 'i-lucide-scroll-text',
    desc: 'Arahan dinas terkait.',
    pengurus: 'Full Akses',
    anggota: 'Read-only',
    tamu: 'Read-only',
  },
  {
    id: '15',
    title: 'Catatan Kejadian',
    icon: 'i-lucide-clipboard-list',
    desc: 'Log insiden penting.',
    pengurus: 'Full Akses',
    anggota: 'Read-only',
    tamu: 'Read-only',
  },
  {
    id: '16',
    title: 'Agenda & Ekspedisi',
    icon: 'i-lucide-calendar-days',
    desc: 'Surat menyurat & jadwal.',
    pengurus: 'Full Akses',
    anggota: 'Read-only',
    tamu: 'Read-only',
  },
]